version: "3"

services:
  drone-server:
    container_name: drone-server
    image: drone/drone
    restart: always
    volumes:
      - db-data:/var/lib/drone/
    env_file:
      - .env
    environment:
      - DRONE_DEBUG=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${RELAY_HOST}
      - DRONE_SERVER_PROTO=http
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_USER_CREATE=username:${DRONE_ADMIN},admin:true

  drone-agent:
    container_name: drone-agent
    image: drone/agent
    restart: always
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - DRONE_RPC_HOST=${RELAY_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME="local"
    depends_on:
      - drone-server

  relay-agent:
    container_name: relay-agent
    image: webhookrelay/webhookrelayd
    restart: always
    command:
      - --mode 
      - tunnel
    env_file:
      - .env
    environment:
      - KEY=${RELAY_KEY}
      - SECRET=${RELAY_SECRET}
    depends_on:
      - drone-server

volumes:
  db-data:
